### ISSUE TITLE
Incluir botões para finalizar chamado (2ª Iteração)

### ISSUE THREAD

**Issue by messias-henrique** [ES2-UFPI/Equipac#14]
Botão para que o bolsista finalize um chamado.

**Comment by VictorCampelo** [comment]
Pode-se criar novas issue para a adição das logicas para a criação desse botão. @Jorgeluispinho @messias-henrique

**Comment by VictorCampelo** [comment]
@messias-henrique  concluiu, falta so subir o push e fazer o PR
