### ISSUE TITLE
Listar chamados na tela de um bolsista (2ª Iteração)

### ISSUE THREAD

**Issue by messias-henrique** [ES2-UFPI/Equipac#19]
Listar chamados cadastrados pelo usuário na tela do bolsista com todos os dados do usuário.

**Comment by VictorCampelo** [comment]
@Jorgeluispinho @messias-henrique algum impedimento nessa issue? A listagem já está configura para ser exibida. basta apenas configura a index de chamado para retorna os valores do banco e jogar em uma variável. para a listagem usem @foreach para iterar dentro da view .blade através de um <th> ou <tr>.

**Comment by VictorCampelo** [comment]
Algum impedimento nessa issue?
