### ISSUE TITLE
UC3 - Atividade 2 - Cancelamento de um chamado

### ISSUE THREAD

**Issue by messias-henrique** [ES2-UFPI/Equipac#2]

**Comment by VictorCampelo** [comment]
A conclusão dessa atividade dependerá de muitas outras atividades.

**Comment by VictorCampelo** [comment]
No momento essa issue está se desenvolvendo bem, quase todas as pendencias já foram resolvidas, falta apenas a correlação dos eloquents ORM nas models do chamado, problema, usuário, status_chamado e bolsista. Tabela no script já finalizada. Por ultimo, as rotas ja estão configuradas e relacionadas corretamente com a sua respectiva view.
