### ISSUE TITLE
Botão para registrar bolsista somente na tela do supervisor (2ª Iteração)

### ISSUE THREAD

**Issue by messias-henrique** [ES2-UFPI/Equipac#24]
Modificar os registros de bolsistas para ser implementados apenas na tela do supervisor.

**Comment by VictorCampelo** [comment]
@Jorgeluispinho @messias-henrique podem iniciar a criação da tela do supervisor. 
algumas dicas:

- Adicionar novo guard em config/adminLTE.
- Criar tabela no banco de dados (eu posso fazer isso, depois apenas atualizem com um pull).
- Em config/adminLTE adicionar novos campos para o Menu e utilizar o `can `para controlar as exibições do opções no menu.
- Usar um `php artisan make:model models/Supervisor -a` para criar a model Supervisor e seu controller com todos os resources padrões.
- Utilizar middleware para poder controllar as autenticações (essa eu faço em uma nova issue).

**Comment by VictorCampelo** [comment]
- Sugestão de adicionar uma nova Issue "tela supervisor". 
- Analise da criação dessa issue para quebra-la em issues menores.
- A issue #24 seria apenas um pedaço da atividade "tela supervisor"

**Comment by VictorCampelo** [comment]
Com o commit 11c85a7 essa issue foi devidamente revisada.
