### ISSUE TITLE
Remover botão de registrar bolsista da tela principal (2ª Iteração)

### ISSUE THREAD

**Issue by messias-henrique** [ES2-UFPI/Equipac#25]
Na tela de login do bolsista não deverá aparecer a opção de registrar, apenas login.

**Comment by VictorCampelo** [comment]
@Jorgeluispinho esta com alguma dificuldade nessa Issue?

**Comment by VictorCampelo** [comment]
@messias-henrique ou @Jorgeluispinho poderia concluir essa issue ainda hoje? Não vejo dificuldade nela. se tiverem, por favor avisem.
